
jobs:

  #JOB 1:  roda o c贸digo 1
  roda codigo 1:

    docker:
      - image: cimg/python:3.10
    working_directory: ~/repo

    steps:
      # Step 1: obtain repo com GitHub
      - checkout

       #Step 2: cria o ambiente virtual e roda o cod.
      - run:
          name: roda o codigo
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python codigo_1.py


  #JOB 2:  roda o c贸digo 2
  roda codigo 2:

    docker:
      - image: cimg/python:3.10
    working_directory: ~/repo

    steps:
      # Step 1: obtain repo com GitHub
      - checkout

      #Step 2: cria o ambiente virtual e roda o cod.
      - run:
          name: roda o codigo
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python codigo_2.py


  #JOB 3:  roda o c贸digo 3
  roda codigo 3:

    docker:
      - image: cimg/python:3.10
    working_directory: ~/repo

    steps:
      # Step 1: obtain repo com GitHub
      - checkout

       #Step 2: cria o ambiente virtual e roda o cod.
      - run:
          name: roda o codigo
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python codigo_3.py


workflows:
  version: 2
  #build-test-and-deploy:
  roda os c贸digos de teste:
    jobs:
      - roda codigo 1:
          filters:
            tags:
              only:
                - /^t.*/
            branches:
              ignore:        #pode colocar 'ignore'  para iginorar um branch
                - master
