
jobs:

  #JOB 1:  roda o código 1
  roda codigo 1:

    docker:
      - image: cimg/python:3.10
    working_directory: ~/repo

    steps:
      # Step 1: obtain repo com GitHub
      - checkout

       #Step 2: cria o ambiente virtual e roda o cod.
      - run:
          name: roda o codigo
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python codigo_1.py


  #JOB 2:  roda o código 2
  roda codigo 2:

    docker:
      - image: cimg/python:3.10
    working_directory: ~/repo

    steps:
      # Step 1: obtain repo com GitHub
      - checkout

      #Step 2: cria o ambiente virtual e roda o cod.
      - run:
          name: roda o codigo
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python codigo_2.py


  #JOB 3:  roda o código 3
  roda codigo 3:

    docker:
      - image: cimg/python:3.10
    working_directory: ~/repo

    steps:
      # Step 1: obtain repo com GitHub
      - checkout

       #Step 2: cria o ambiente virtual e roda o cod.
      - run:
          name: roda o codigo
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python codigo_3.py


workflows:
  version: 2
  #build-test-and-deploy:
  rotina 1 roda o código:
    jobs:
      - roda codigo 1:
          filters: &anchor_filtro_desenv  #define uma ancora associada a um conteudo
            tags:
              only:
                - /^tag.*/
            branches:
              ignore:        #pode colocar 'ignore'  para iginorar um branch
                - /.*/


  rotina 2 roda o mesmo código:
    jobs:
      - roda codigo 1:
          filters:
            <<: *anchor_filtro_desenv #chama o conteudo associado a uma ancora
